# Generated by Django 5.2.12 on 2026-05-19 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accomplishmentreportlog',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accomplishment_report_logs', to='app.organization'),
        ),
        migrations.AddField(
            model_name='accomplishmentreportlog',
            name='report_title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='accomplishmentreportlog',
            name='action',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('deleted', 'Deleted')], max_length=20),
        ),
        migrations.AlterField(
            model_name='accomplishmentreportlog',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ar_log', to='app.accomplishmentreport'),
        ),
    ]
