# Generated by Django 5.2.12 on 2026-03-31 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_societyfee_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicyear',
            name='semester',
            field=models.CharField(choices=[('1stSem', '1st Semester'), ('2ndSem', '2nd Semester')], max_length=10),
        ),
    ]
