# Generated by Django 5.2.12 on 2026-03-31 05:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_academicyear_semester'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='societyfee',
            unique_together={('student', 'organization', 'academic_year', 'semester')},
        ),
    ]
