# Generated by Django 5.2.12 on 2026-03-31 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_societyfee_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='societyfee',
            name='semester',
            field=models.CharField(choices=[('1stSem', '1st Semester'), ('2ndSem', '2nd Semester')], max_length=50),
        ),
    ]
