# Generated by Django 5.2.12 on 2026-09-01 04:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_badge_studentbadge_studentrewardprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='app.financialreport')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('report', 'student')},
            },
        ),
    ]
