# Generated by Django 5.2.12 on 2026-03-31 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_societyfee_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='society_amount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
