# Generated by Django 5.2.12 on 2026-03-31 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_organization_society_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='society_amount',
            new_name='society_fee_amount',
        ),
    ]
