# Generated by Django 5.2.12 on 2026-03-31 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_society_amount_organization_society_fee_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='society_fee_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
