# Generated by Django 5.2.12 on 2026-09-20 03:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_accomplishmentreportcomments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accomplishmentreportcomments',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='app.accomplishmentreport'),
        ),
    ]
