# Generated by Django 5.2.12 on 2026-09-20 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_accomplishmentreportcomments_report'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accomplishmentreportcomments',
            old_name='date',
            new_name='created_at',
        ),
    ]
