# Generated by Django 5.2.12 on 2026-04-01 14:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_organization_society_fee_amount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Heads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(blank=True, max_length=20, null=True)),
                ('department', models.CharField(choices=[('osas', 'Office of Student Affairs and Service'), ('sds', 'Student Development and Services')], max_length=50)),
                ('campus', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='heads', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
