# Generated by Django 5.2.12 on 2026-09-22 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_date_accomplishmentreportcomments_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='program',
            field=models.CharField(blank=True, choices=[('BSIT', 'Bachelor of Science in Information Technology'), ('BSCS', 'Bachelor of Science in Computer Science'), ('BSP', 'Bachelor of Science in Psychology'), ('BSED', 'Bachelor of Secondary Education'), ('BSHM', 'Bachelor of Science in Hospitality Management'), ('BSC', 'Bachelor of Science in Criminology'), ('BSBA-MM', 'Bachelor of Science in Bussiness Administration - Marketing Management'), ('BSBA-HR', 'Bachelor of Science in Bussiness Admisnistration - Human Resource Management'), ('all_program', 'All Program')], null=True),
        ),
    ]
