# Generated by Django 5.2.12 on 2026-04-02 11:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rename_heads_head'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_auditor', 'Pending Auditor'), ('pending_president', 'Pending President'), ('pending_adviser', 'Pending Adviser'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('on_blockchain', 'On Blockchain')], default='draft', max_length=30)),
                ('auditor_approved_at', models.DateTimeField(blank=True, null=True)),
                ('auditor_remarks', models.TextField(blank=True, null=True)),
                ('president_approved_at', models.DateTimeField(blank=True, null=True)),
                ('president_remarks', models.TextField(blank=True, null=True)),
                ('adviser_approved_at', models.DateTimeField(blank=True, null=True)),
                ('adviser_remarks', models.TextField(blank=True, null=True)),
                ('blockchain_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('blockchain_recorded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_reports', to='app.academicyear')),
                ('adviser_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adviser_approved_reports', to=settings.AUTH_USER_MODEL)),
                ('auditor_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditor_approved_reports', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reports', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_reports', to='app.organization')),
                ('president_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='president_approved_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FinancialReportEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('category', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('order', models.PositiveIntegerField(default=0)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='app.financialreport')),
            ],
            options={
                'ordering': ['date', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ReportApprovalLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('blockchain', 'Recorded on Blockchain')], max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('action_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_logs', to='app.financialreport')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
