# Generated by Django 5.2.12 on 2026-09-22 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_organization_program'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='program',
            field=models.CharField(choices=[('BSIT', 'Bachelor of Science in Information Technology'), ('BSCS', 'Bachelor of Science in Computer Science'), ('BSP', 'Bachelor of Science in Psychology'), ('BSED-MTH', 'Bachelor of Secondary Education - Mathematics '), ('BSED-ENG', 'Bachelor of Secondary Education - English'), ('BSHM', 'Bachelor of Science in Hospitality Management'), ('BSC', 'Bachelor of Science in Criminology'), ('BSBA-MM', 'Bachelor of Science in Bussiness Administration - Marketing Management'), ('BSBA-HR', 'Bachelor of Science in Bussiness Admisnistration - Human Resource Management')], max_length=20),
        ),
    ]
