# Generated by Django 5.2.12 on 2026-04-04 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_financialreport_financialreportentry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialreportentry',
            name='entry_type',
            field=models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], default='expense', max_length=10),
        ),
        migrations.AddField(
            model_name='financialreportentry',
            name='income_source',
            field=models.CharField(blank=True, choices=[('society', 'Society Fee'), ('other', 'Other Income')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='financialreportentry',
            name='society_fee_per_student',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='financialreportentry',
            name='society_semester',
            field=models.CharField(blank=True, choices=[('1stSem', '1st Semester'), ('2ndSem', '2nd Semester')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='financialreportentry',
            name='society_student_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
