# Generated by Django 5.2.12 on 2026-04-09 14:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_organization_balance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='financialreport',
            name='co_adviser_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financialreport',
            name='co_adviser_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='co_adviser_approved_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='financialreport',
            name='co_adviser_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financialreport',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_auditor', 'Pending Auditor'), ('pending_president', 'Pending President'), ('pending_adviser', 'Pending Adviser'), ('pending_co_adviser', 'Pending Co-Adviser'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('on_blockchain', 'On Blockchain')], default='draft', max_length=30),
        ),
    ]
