# Generated by Django 5.2.12 on 2026-04-09 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_financialreport_co_adviser_approved_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adviser',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.organization'),
        ),
    ]
