# Generated by Django 5.2.12 on 2026-04-10 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_financialreportentry_entry_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='program',
            field=models.CharField(blank=True, choices=[('BSIT', 'Bachelor of Science in Information Technology'), ('BSCS', 'Bachelor of Science in Computer Science'), ('BSP', 'Bachelor of Science in Psychology'), ('BSED-MTH', 'Bachelor of Secondary Education - Mathematics '), ('BSED-ENG', 'Bachelor of Secondary Education - English'), ('BSHM', 'Bachelor of Science in Hospitality Management'), ('BSC', 'Bachelor of Science in Criminology'), ('BSBA-MM', 'Bachelor of Science in Bussiness Administration - Marketing Management'), ('BSBA-HR', 'Bachelor of Science in Bussiness Admisnustration - Human Resource Management'), ('all_program', 'All Program')], null=True),
        ),
    ]
