# Generated by Django 5.2.12 on 2026-04-11 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_product_organization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='sku',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='stock',
        ),
    ]
