# Generated by Django 5.2.12 on 2026-04-15 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_financialreportentry_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialreportentry',
            name='variant',
        ),
        migrations.AddField(
            model_name='financialreportentry',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
