# Generated by Django 5.2.12 on 2026-04-15 03:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_remove_financialreportentry_variant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialreportentry',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.productvariant'),
        ),
    ]
