# Generated by Django 5.2.12 on 2026-04-22 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_globalannouncement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='category',
            field=models.CharField(choices=[('academic', 'Academic'), ('non_academic', 'Non-Academic'), ('performing_arts', 'Performing Arts'), ('student_council', 'Student Council'), ('student_publication', 'Student Publication')], max_length=50),
        ),
    ]
