# Generated by Django 5.2.12 on 2026-04-23 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_alter_organization_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('regular', 'Regular'), ('irregular', 'Irregular')], default=0),
            preserve_default=False,
        ),
    ]
