# Generated by Django 5.2.12 on 2026-04-28 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_accomplismentreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='accomplismentreport',
            name='report_file',
            field=models.FileField(blank=True, null=True, upload_to='accomplishment_reports/'),
        ),
    ]
