# Generated by Django 5.2.12 on 2026-04-27 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_accomplismentreport_report_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accomplismentreport',
            options={'ordering': ['-created_at']},
        ),
    ]
