# Generated by Django 5.2.12 on 2026-04-30 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_alter_accomplismentreport_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='officer',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/officers'),
        ),
    ]
