# Generated by Django 5.2.12 on 2026-04-30 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_officer_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='adviser',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/advisers'),
        ),
    ]
