# Generated by Django 5.2.12 on 2026-04-30 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_remove_student_organization_student_organization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='organization',
        ),
        migrations.AddField(
            model_name='student',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.organization'),
        ),
    ]
