# Generated by Django 5.2.12 on 2026-04-30 19:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_remove_student_organization_student_organization'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AccomplismentReport',
            new_name='AccomplishmentReport',
        ),
    ]
