# Generated by Django 5.2.12 on 2026-05-01 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_rename_accomplismentreport_accomplishmentreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='other_organization',
            field=models.ManyToManyField(blank=True, null=True, related_name='other_students', to='app.organization'),
        ),
    ]
