# Generated by Django 5.2.12 on 2026-05-03 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_student_other_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='product_img',
            field=models.ImageField(default=0, upload_to='product_image/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='financialreportentry',
            name='income_source',
            field=models.CharField(blank=True, choices=[('society', 'Society Fee'), ('product', 'Product Sale'), ('voluntary', 'Voluntary Funds'), ('other', 'Other Income')], max_length=20, null=True),
        ),
    ]
