# Generated by Django 5.2.12 on 2026-05-16 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_accomplishmentreportlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='other_organization',
            field=models.ManyToManyField(blank=True, related_name='other_students', to='app.organization'),
        ),
    ]
