# Generated by Django 5.2.12 on 2026-05-18 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_alter_organization_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialreportentry',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
