# Generated by Django 5.2.12 on 2026-04-09 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('campus_admin', 'Campus Admin'), ('adviser', 'Adviser'), ('co_adviser', 'Co-Adviser'), ('treasurer', 'Treasurer'), ('auditor', 'Auditor'), ('president', 'President'), ('secretary', 'Secretary'), ('student', 'Student'), ('head', 'Head')], max_length=20),
        ),
    ]
