# Generated by Django 5.2.12 on 2026-04-25 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_middle_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('campus_admin', 'Campus Admin'), ('adviser', 'Adviser'), ('co_adviser', 'Co-Adviser'), ('treasurer', 'Treasurer'), ('auditor', 'Auditor'), ('president', 'President'), ('vice_president', 'Vice-President'), ('secretary', 'Secretary'), ('student', 'Student'), ('head', 'Head')], max_length=20),
        ),
    ]
